[package]
name = "flowable-app-engine"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license.workspace = true

[features]
postgres = ["flowable-persistence/postgres"]
mysql = ["flowable-persistence/mysql"]

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
uuid = { version = "1.23.1", features = ["v4"] }
flowable-app-converter = { path = "../flowable-app-converter" }
flowable-app-model = { path = "../flowable-app-model" }
flowable-persistence = { path = "../flowable-persistence" }
