[package]
name = "flowable-dmn-engine"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license.workspace = true

[features]
postgres = ["flowable-persistence/postgres"]
mysql = ["flowable-persistence/mysql"]

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
regex = "1.12.2"
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
uuid = { version = "1.23.1", features = ["v4"] }
flowable-dmn-model = { version = "0.1.0", path = "../flowable-dmn-model" }
flowable-engine-common = { path = "../flowable-engine-common" }
flowable-persistence = { version = "0.1.0", path = "../flowable-persistence" }
