[package]
name = "flowable-bpmn-converter"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license.workspace = true

[dependencies]
tracing = "0.1"
flowable-bpmn-model = { version = "0.1.0", path = "../flowable-bpmn-model" }
flowable-engine-common = { version = "0.1.0", path = "../flowable-engine-common" }
indexmap = "2.14.0"
quick-xml = "0.39.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
uuid = { version = "1.23.1", features = ["v4"] }
