//! Versioned JSON documents exchanged between the first-party modeler UI and
//! Rust services.
//!
//! The nested models are the engine's canonical Rust models. These envelopes
//! add protocol evolution without introducing a second semantic model.

use flowable_bpmn_model::BpmnModel;
use flowable_dmn_model::DmnDefinition;
use flowable_form_service::FormModel;
use schemars::{JsonSchema, Schema, schema_for};
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

/// Current editor protocol version.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub enum ProtocolVersion {
    #[default]
    #[serde(rename = "1.0")]
    #[schemars(rename = "1.0")]
    V1,
}

#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BpmnEditorDocument {
    pub schema_version: ProtocolVersion,
    pub model: BpmnModel,
}

impl BpmnEditorDocument {
    pub fn new(model: BpmnModel) -> Self {
        Self {
            schema_version: ProtocolVersion::V1,
            model,
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DmnEditorDocument {
    pub schema_version: ProtocolVersion,
    pub model: DmnDefinition,
}

impl DmnEditorDocument {
    pub fn new(model: DmnDefinition) -> Self {
        Self {
            schema_version: ProtocolVersion::V1,
            model,
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct FormEditorDocument {
    pub schema_version: ProtocolVersion,
    pub model: FormModel,
}

impl FormEditorDocument {
    pub fn new(model: FormModel) -> Self {
        Self {
            schema_version: ProtocolVersion::V1,
            model,
        }
    }
}

/// Schema-only root that keeps all three editor document definitions in one
/// generated artifact. API handlers use the concrete document types above.
#[derive(JsonSchema)]
#[schemars(rename = "FlowableModelerEditorProtocol")]
pub struct EditorProtocolSchema {
    pub bpmn: BpmnEditorDocument,
    pub dmn: DmnEditorDocument,
    pub form: FormEditorDocument,
}

pub fn editor_protocol_schema() -> Schema {
    schema_for!(EditorProtocolSchema)
}

pub fn editor_protocol_schema_json() -> Result<String, serde_json::Error> {
    let mut schema = serde_json::to_value(editor_protocol_schema())?;
    normalize_ref_siblings(&mut schema);
    serde_json::to_string_pretty(&schema)
}

/// Rewrites `$ref` objects that also carry schema keywords as an explicit
/// `allOf`. JSON Schema 2020-12 allows siblings next to `$ref`, but the TypeScript
/// generator intentionally targets older drafts and otherwise drops the sibling
/// discriminator generated by `schemars` for internally tagged Rust enums.
fn normalize_ref_siblings(value: &mut Value) {
    if let Value::Object(object) = value {
        if object.contains_key("$ref") && object.len() > 1 {
            let reference = object.remove("$ref").expect("checked above");
            let siblings = Value::Object(std::mem::take(object));
            object.insert(
                "allOf".to_string(),
                Value::Array(vec![
                    Value::Object(Map::from_iter([("$ref".to_string(), reference)])),
                    siblings,
                ]),
            );
        }

        for child in object.values_mut() {
            normalize_ref_siblings(child);
        }
    } else if let Value::Array(items) = value {
        for item in items {
            normalize_ref_siblings(item);
        }
    }
}
