[package]
name = "flowable-image-generator"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license.workspace = true

[dependencies]
flowable-bpmn-layout = { path = "../flowable-bpmn-layout" }
flowable-bpmn-model = { path = "../flowable-bpmn-model" }
resvg = { version = "0.47.0", default-features = false, features = ["system-fonts", "text"] }

[dev-dependencies]
flowable-bpmn-converter = { path = "../flowable-bpmn-converter" }
