[package]
name = "flowable-cmmn-image-generator"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license.workspace = true

[dependencies]
flowable-cmmn-model = { path = "../flowable-cmmn-model" }
flowable-cmmn-engine = { path = "../flowable-cmmn-engine" }

[dev-dependencies]
flowable-cmmn-converter = { path = "../flowable-cmmn-converter" }
