[package]
name = "flowable-dmn-converter"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license.workspace = true

[dependencies]
flowable-dmn-model = { version = "0.1.0", path = "../flowable-dmn-model" }
roxmltree = "0.20.0"
quick-xml = "0.39.2"

[dev-dependencies]
serde_json = "1.0.149"
