import type {
  ArtifactEnum,
  BpmnEditorDocument,
  FlowElementEnum,
  GraphicInfo,
} from '../generated/editor-protocol';

const baseElement = (id: string) => ({
  id,
  xmlRowNumber: 0,
  xmlColumnNumber: 0,
  extensionElements: {},
  attributes: {},
});

const flowNode = (id: string, name: string) => ({
  ...baseElement(id),
  name,
  documentation: null,
  executionListeners: [],
  asynchronous: false,
  asynchronousLeave: false,
  notExclusive: false,
  asynchronousLeaveNotExclusive: false,
  exclusive: true,
  asynchronousLeaveExclusive: false,
  incomingFlows: [],
  outgoingFlows: [],
});

const activity = (id: string, name: string) => ({
  ...flowNode(id, name),
  failedJobRetryTimeCycleValue: null,
  defaultFlow: null,
  isForCompensation: false,
  forCompensation: false,
  loopCharacteristics: null,
  dataInputAssociations: [],
  dataOutputAssociations: [],
  mapExceptions: [],
  boundaryEvents: [],
  fieldExtensions: [],
});

const sequence = (id: string, sourceRef: string, targetRef: string, name?: string) =>
  ({
    elementType: 'sequenceFlow',
    ...baseElement(id),
    name: name ?? null,
    documentation: null,
    executionListeners: [],
    conditionExpression: name ? '${approved}' : null,
    conditionLanguage: null,
    sourceRef,
    targetRef,
    skipExpression: null,
    waypoints: [],
  }) satisfies FlowElementEnum;

const elements: FlowElementEnum[] = [
  {
    elementType: 'startEvent',
    ...flowNode('start', 'Request received'),
    eventDefinitions: [],
    initiator: null,
    formKey: null,
    sameDeployment: true,
    interrupting: true,
  },
  {
    elementType: 'userTask',
    ...activity('review', 'Review request'),
    assignee: null,
    owner: null,
    priority: '50',
    category: null,
    formKey: 'leaveRequest',
    dueDate: null,
    businessCalendarName: null,
    candidateUsers: [],
    candidateGroups: ['managers'],
    formProperties: [],
    taskListeners: [],
    skipExpression: null,
    extended: false,
    extensionId: null,
    sameDeployment: true,
    validateFormFields: null,
    taskIdVariableName: null,
    taskCompleterVariableName: null,
  },
  {
    elementType: 'complexGateway',
    ...flowNode('decision', 'Approved?'),
    defaultFlow: 'reworkFlow',
    activationCondition: '${approvedCount >= 2}',
  },
  {
    elementType: 'serviceTask',
    ...activity('notify', 'Notify employee'),
    implementation: '${notificationDelegate}',
    implementationType: 'delegateExpression',
    formKey: null,
    validateFormFields: null,
    resultVariableName: null,
    parallelInSameTransaction: null,
    type: null,
    topic: null,
    doNotIncludeVariables: false,
    eventType: null,
    triggerEventType: null,
    sendSynchronously: false,
    extensionId: null,
    skipExpression: null,
    useLocalScopeForResultVariable: false,
    triggerable: false,
    extended: false,
    storeResultVariableAsTransient: false,
    inParameters: [],
    outParameters: [],
    eventInParameters: [],
    eventOutParameters: [],
    httpRequestHandler: null,
    httpResponseHandler: null,
  },
  {
    elementType: 'endEvent',
    ...flowNode('end', 'Completed'),
    eventDefinitions: [],
  },
  {
    elementType: 'boundaryEvent',
    ...flowNode('reviewTimer', 'Escalation timer'),
    attachedToRefId: 'review',
    cancelActivity: false,
    inParameters: [],
    outParameters: [],
    eventDefinitions: [
      {
        eventDefinitionType: 'timerEventDefinition',
        ...baseElement('reviewTimerDefinition'),
        timeDuration: 'PT48H',
        timeDate: null,
        timeCycle: null,
        calendarName: null,
        endDate: null,
      },
    ],
  },
  sequence('requestFlow', 'start', 'review'),
  sequence('decisionFlow', 'review', 'decision'),
  sequence('approvedFlow', 'decision', 'notify', 'Approved'),
  sequence('completeFlow', 'notify', 'end'),
];

const artifacts: ArtifactEnum[] = [
  {
    artifactType: 'textAnnotation',
    ...baseElement('approvalNote'),
    text: 'Two approvals are required',
    textFormat: 'text/plain',
  },
  {
    artifactType: 'group',
    ...baseElement('approvalGroup'),
    categoryValueRef: 'approvalCategory',
  },
  {
    artifactType: 'association',
    ...baseElement('approvalLink'),
    sourceRef: 'approvalNote',
    targetRef: 'decision',
    associationDirection: 'One',
  },
];

const location = (x: number, y: number, width: number, height: number): GraphicInfo => ({
  x,
  y,
  width,
  height,
  rotation: 0,
  expanded: true,
  xmlRowNumber: 0,
  xmlColumnNumber: 0,
});

const waypoint = (x: number, y: number): GraphicInfo => location(x, y, 0, 0);

export const sampleDocument: BpmnEditorDocument = {
  schemaVersion: '1.0',
  model: {
    definitionsAttributes: {},
    processes: [
      {
        ...baseElement('leaveProcess'),
        name: 'Leave approval',
        executable: true,
        documentation: 'A representative Flowable process rendered from the editor protocol.',
        ioSpecification: null,
        executionListeners: [],
        lanes: [
          {
            ...baseElement('managerLane'),
            name: 'Manager',
            flowReferences: ['review', 'decision'],
          },
          {
            ...baseElement('systemLane'),
            name: 'Automation',
            flowReferences: ['notify'],
          },
        ],
        dataObjects: [],
        candidateStarterUsers: [],
        candidateStarterGroups: [],
        eventListeners: [],
        enableEagerExecutionTreeFetching: false,
        flowElements: elements,
        flowElementMap: Object.fromEntries(
          elements
            .filter((element) => element.id)
            .map((element) => [element.id as string, element]),
        ),
        artifacts,
        artifactMap: Object.fromEntries(
          artifacts.map((artifact) => [artifact.id as string, artifact]),
        ),
      },
    ],
    locationMap: {
      leavePool: location(72, 72, 1180, 430),
      managerLane: location(112, 72, 1140, 230),
      systemLane: location(112, 302, 1140, 200),
      start: location(172, 164, 42, 42),
      review: location(304, 135, 156, 100),
      decision: location(554, 153, 66, 66),
      notify: location(744, 352, 164, 100),
      end: location(1032, 381, 46, 46),
      reviewTimer: location(410, 214, 34, 34),
      approvalNote: location(452, 82, 180, 54),
      approvalGroup: location(282, 112, 370, 158),
    },
    labelLocationMap: {
      start: location(145, 214, 96, 24),
      decision: location(535, 226, 104, 24),
      end: location(1009, 437, 92, 24),
      approvedFlow: location(635, 270, 90, 24),
    },
    flowLocationMap: {
      requestFlow: [waypoint(214, 185), waypoint(304, 185)],
      decisionFlow: [waypoint(460, 185), waypoint(554, 185)],
      approvedFlow: [
        waypoint(620, 186),
        waypoint(684, 186),
        waypoint(684, 402),
        waypoint(744, 402),
      ],
      completeFlow: [waypoint(908, 402), waypoint(1032, 402)],
      approvalLink: [waypoint(542, 136), waypoint(587, 153)],
    },
    edgeMap: {},
    signals: [],
    pools: [
      {
        ...baseElement('leavePool'),
        name: 'Leave approval',
        processRef: 'leaveProcess',
        executable: true,
      },
    ],
    imports: [],
    interfaces: [],
    globalArtifacts: [],
    resources: [],
    targetNamespace: 'https://flowable.org/modeler/sample',
    sourceSystemId: 'flowable-modeler',
    userTaskFormTypes: null,
    startEventFormTypes: null,
    exporter: 'Flowable Modeler',
    exporterVersion: '1.0',
    messages: [],
    errors: {},
    namespaces: {},
    dataStores: {},
    messageFlows: {},
    escalations: [],
    itemDefinitions: {},
    mainProcess: null,
  },
};
